# Generated by Django 4.0.8 on 2024-09-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('level', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Elementary', 'Elementary'), ('Middle School', 'Middle School'), ('High School', 'High School')], max_length=25, null=True)),
                ('year', models.IntegerField(choices=[(0, 'Kindergarten'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='courseallocation',
            old_name='Subjects',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='course.subjects'),
        ),
        migrations.AddField(
            model_name='courseallocation',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='allocated_subjects', to='course.subjects'),
        ),
    ]
