# Generated by Django 4.0.8 on 2025-02-24 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentreminder',
            unique_together={('student', 'fee_structure', 'reminder_date')},
        ),
    ]
