# Generated by Django 4.0.8 on 2025-03-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_payment_status_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentReminder',
        ),
    ]
