# Generated by Django 4.0.8 on 2025-03-28 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fees.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0005_student_feestructure_term_feestatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(default=fees.models.get_default_payer, on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='fees.student'),
        ),
    ]
