# Generated by Django 4.0.8 on 2025-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_academicyear_alter_feecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
