# Generated by Django 4.0.8 on 2024-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_lab_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_office_assistant',
            field=models.BooleanField(default=False),
        ),
    ]
