# Generated by Django 4.0.8 on 2025-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_office_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Other', 'Other')], max_length=20),
        ),
    ]
